import type { Routine, Folder } from './types';
import { useState, useRef, useEffect } from 'react';
import type { Item, Exercise } from '../exercises/types';
import { api } from '../../shared/api/client';
import type { FormEvent } from 'react';
import { RestTimeField } from './RestTimeField';

export function RoutineEditor({ routine, folders, close, done }: { routine: Routine; folders: Folder[]; close: () => void; done: () => Promise<void> }) {
    const [name, setName] = useState(routine.name), [folder, setFolder] = useState(String(routine.folder_id ?? folders[0]?.id ?? '')), [items, setItems] = useState<Item[]>(routine.exercises), [q, setQ] = useState(''), [results, setResults] = useState<Exercise[]>([]);
    const [builderPage, setBuilderPage] = useState(0), mobilePages = useRef<HTMLDivElement>(null);
    useEffect(() => { if (q.trim().length < 2) { setResults([]); return; } const timer = setTimeout(() => void api<Exercise[]>(`/exercises?q=${encodeURIComponent(q.trim())}`).then(setResults).catch(() => setResults([])), 250); return () => clearTimeout(timer); }, [q]);
    const update = (index: number, field: keyof Item, value: number) => setItems(items.map((item, i) => i === index ? { ...item, [field]: value } : item));
    const addExercise = (exercise: Exercise) => { if (!items.some(item => item.exercise_id === exercise.id || item.exercise?.id === exercise.id)) setItems([...items, { exercise_id: exercise.id, exercise, name: exercise.name, planned_sets: 3, target_reps_min: 8, target_reps_max: 12, rest_seconds: 90 }]); setQ(''); setResults([]); };
    const save = async (event: FormEvent) => { event.preventDefault(); await api(routine.scheduled_on ? `/calendar/${routine.scheduled_on}/routine/${routine.id}` : routine.id ? `/routines/${routine.id}` : '/routines', { method: routine.id ? 'PUT' : 'POST', body: JSON.stringify({ name, folder_id: Number(folder), exercises: items.map(item => ({ exercise_id: item.exercise_id ?? item.exercise?.id, planned_sets: item.planned_sets ?? 3, target_reps_min: item.target_reps_min ?? item.target_reps ?? 8, target_reps_max: item.target_reps_max ?? item.target_reps ?? 12, rest_seconds: item.rest_seconds ?? 90, target_weight: item.target_weight })) }) }); await done(); };
    const exerciseName = (item: Item) => item.exercise?.name ?? item.name;
    const muscleName = (item: Item) => item.exercise?.primary_muscle ?? item.primary_muscle ?? 'Unmapped muscle';
    const goToPage = (page: number) => { const pages = mobilePages.current; if (pages) pages.scrollTo({ left: page * pages.clientWidth, behavior: 'smooth' }); setBuilderPage(page); };
    return <div className="back"><form className="modal routine-editor rest-editor" onSubmit={save}><div className="modal-head"><div><p className="overline">WORKOUT DAY BUILDER</p><h2>{routine.scheduled_on ? 'Edit planned workout' : routine.id ? 'Edit workout day' : 'New workout day'}</h2>{routine.scheduled_on && <p>{routine.scheduled_on} · Changes apply only to this workout.</p>}</div><button type="button" onClick={close}>×</button></div><div className="builder-basics"><label>DAY NAME<input value={name} onChange={event => setName(event.target.value)}/></label><label>{routine.scheduled_on ? 'DATE' : 'FOLDER'}{routine.scheduled_on ? <input readOnly value={routine.scheduled_on}/> : <select value={folder} onChange={event => setFolder(event.target.value)}>{folders.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}</label></div><label className="add-exercise-label">ADD EXERCISE<input value={q} onChange={event => setQ(event.target.value)} placeholder="Search exercises, e.g. bench press"/></label><div className="search">{results.map(item => <button type="button" key={item.id} onClick={() => addExercise(item)}><span><b>{item.name}</b><small>{item.primary_muscle ?? 'Unmapped'} · {item.equipment}</small></span>＋</button>)}</div>
        <div className="rest-builder-list desktop-rest-builder"><div className="rest-builder-head"><span>EXERCISE</span><span>SETS</span><span>REPS</span><span>REST</span><span /></div>{items.map((item, index) => <div className="rest-builder-row" key={`${item.exercise_id ?? item.exercise?.id}-${index}`}><div><b>{exerciseName(item)}</b><small>{muscleName(item)}</small></div><input aria-label={`${item.name} sets`} inputMode="numeric" value={item.planned_sets ?? ''} onChange={event => update(index, 'planned_sets', Number(event.target.value))}/><div className="rest-reps"><input aria-label={`${item.name} minimum reps`} inputMode="numeric" value={item.target_reps_min ?? item.target_reps ?? ''} onChange={event => update(index, 'target_reps_min', Number(event.target.value))}/><span>–</span><input aria-label={`${item.name} maximum reps`} inputMode="numeric" value={item.target_reps_max ?? item.target_reps ?? ''} onChange={event => update(index, 'target_reps_max', Number(event.target.value))}/></div><RestTimeField seconds={item.rest_seconds ?? 90} name={item.name} onChange={seconds => update(index, 'rest_seconds', seconds)}/><button type="button" aria-label={`Remove ${item.name}`} onClick={() => setItems(items.filter((_, i) => i !== index))}>×</button></div>)}</div>
        <div className="mobile-rest-builder"><div className="mobile-builder-pages" ref={mobilePages} onScroll={event => { const element = event.currentTarget; setBuilderPage(Math.round(element.scrollLeft / element.clientWidth)); }}>
            <section className="mobile-builder-page" aria-label="Sets and reps"><div className="mobile-builder-head"><span>EXERCISE</span><span>SETS</span><span>REPS</span><span /></div>{items.map((item, index) => <div className="mobile-builder-row mobile-builder-targets" key={`${item.exercise_id ?? item.exercise?.id}-${index}`}><div><b>{exerciseName(item)}</b><small>{muscleName(item)}</small></div><input aria-label={`${item.name} sets`} inputMode="numeric" value={item.planned_sets ?? ''} onChange={event => update(index, 'planned_sets', Number(event.target.value))}/><div className="rest-reps"><input aria-label={`${item.name} minimum reps`} inputMode="numeric" value={item.target_reps_min ?? item.target_reps ?? ''} onChange={event => update(index, 'target_reps_min', Number(event.target.value))}/><span>–</span><input aria-label={`${item.name} maximum reps`} inputMode="numeric" value={item.target_reps_max ?? item.target_reps ?? ''} onChange={event => update(index, 'target_reps_max', Number(event.target.value))}/></div><button type="button" aria-label={`Remove ${item.name}`} onClick={() => setItems(items.filter((_, i) => i !== index))}>×</button></div>)}</section>
            <section className="mobile-builder-page" aria-label="Rest times"><div className="mobile-builder-head mobile-rest-head"><span>EXERCISE</span><span>REST</span></div>{items.map((item, index) => <div className="mobile-builder-row mobile-builder-rest" key={`${item.exercise_id ?? item.exercise?.id}-${index}`}><div><b>{exerciseName(item)}</b><small>{muscleName(item)}</small></div><RestTimeField seconds={item.rest_seconds ?? 90} name={item.name} onChange={seconds => update(index, 'rest_seconds', seconds)}/></div>)}</section>
        </div><div className="mobile-builder-nav" aria-label="Workout builder pages"><button type="button" className={builderPage === 0 ? 'active' : ''} aria-label="Show sets and reps" aria-current={builderPage === 0 ? 'page' : undefined} onClick={() => goToPage(0)}><span />SETS &amp; REPS</button><button type="button" className={builderPage === 1 ? 'active' : ''} aria-label="Show rest times" aria-current={builderPage === 1 ? 'page' : undefined} onClick={() => goToPage(1)}><span />REST</button></div><p className="mobile-swipe-hint">Swipe sideways to switch pages</p><button className="primary wide mobile-builder-save">Save workout day →</button></div>
        <p className="builder-tip">Choose the rest period for each exercise. The workout timer will use it after a set.</p><button className="primary wide desktop-builder-save">Save workout day →</button></form></div>;
}
