import type { Folder, Routine } from '../routines/types';
import type { Workout } from '../workout/types';
import type { CalendarMonth, LoadCalendarMonth } from './types';
import { useState } from 'react';
import { api } from '../../shared/api/client';
import { TrainingCalendar } from './TrainingCalendar';
import { duration } from '../../shared/lib/format';
import { WorkoutLogger } from '../workout/WorkoutLogger';

export function Calendar({ folders, history, months, loadMonth, onWorkoutSaved, start, repeatWorkout }: { folders: Folder[]; history: Workout[]; months: Record<string, CalendarMonth>; loadMonth: LoadCalendarMonth; onWorkoutSaved: (date: string) => Promise<void>; start: (routine: Routine) => Promise<void>; repeatWorkout: (workout: Workout) => Promise<void> }) {
    const [editWorkout, setEditWorkout] = useState<Workout | null>(null);
    const [viewWorkout, setViewWorkout] = useState<Workout | null>(null);
    const [noteWorkout, setNoteWorkout] = useState<Workout | null>(null);
    const [noteDraft, setNoteDraft] = useState('');
    const [noteSaving, setNoteSaving] = useState(false);
    const saveNote = async () => { if (!noteWorkout?.id) return; setNoteSaving(true); try { await api(`/workouts/${noteWorkout.id}`, { method: 'PATCH', body: JSON.stringify({ ...noteWorkout, note: noteDraft }) }); await onWorkoutSaved(noteWorkout.performed_on); setNoteWorkout(null); } finally { setNoteSaving(false); } };
    return <><TrainingCalendar folders={folders} history={history} months={months} loadMonth={loadMonth} start={start} repeatWorkout={repeatWorkout} viewWorkout={setViewWorkout} editWorkout={setEditWorkout} addNote={workout => { setNoteWorkout(workout); setNoteDraft(workout.note ?? ''); }}/>{viewWorkout && <div className="back calendar-view-overlay"><article className="calendar-view-panel" role="dialog" aria-modal="true" aria-label="Workout details"><header><div><small>{viewWorkout.performed_on} · COMPLETED</small><h2>{viewWorkout.name}</h2><p>{viewWorkout.exercises.reduce((total, exercise) => total + (exercise.sets?.length ?? 0), 0)} sets · {duration(viewWorkout.duration_seconds)}</p></div><button aria-label="Close workout details" onClick={() => setViewWorkout(null)}>×</button></header>{viewWorkout.note && <p className="calendar-view-note">{viewWorkout.note}</p>}<div className="calendar-view-exercises">{viewWorkout.exercises.map((exercise, index) => <section key={`${exercise.name}-${index}`}><h3>{exercise.name}</h3><p>{(exercise.sets ?? []).map(set => `${set.weight} kg × ${set.reps}`).join(' · ') || 'No sets logged'}</p>{exercise.note && <small>{exercise.note}</small>}</section>)}</div><footer><button onClick={() => { setEditWorkout(viewWorkout); setViewWorkout(null); }}>Edit workout</button></footer></article></div>}{noteWorkout && <div className="back calendar-note-overlay"><form className="calendar-note-panel" role="dialog" aria-modal="true" aria-label="Workout note" onSubmit={event => { event.preventDefault(); void saveNote(); }}><header><h2>Workout note</h2><button type="button" aria-label="Close note" onClick={() => setNoteWorkout(null)}>×</button></header><p>{noteWorkout.name} · {noteWorkout.performed_on}</p><textarea autoFocus maxLength={1000} value={noteDraft} onChange={event => setNoteDraft(event.target.value)} placeholder="How did this workout go?"/><footer><button type="button" onClick={() => setNoteWorkout(null)}>Cancel</button><button className="primary" disabled={noteSaving}>{noteSaving ? 'Saving…' : 'Save note'}</button></footer></form></div>}{editWorkout && <div className="back calendar-editor"><div className="calendar-editor-panel"><WorkoutLogger workout={editWorkout} folders={folders} active={[]} start={start} startAdHoc={async () => undefined} setWorkout={setEditWorkout} editing finish={async () => undefined} saveEdit={async workout => { await api(`/workouts/${workout.id}`, { method: 'PATCH', body: JSON.stringify(workout) }); setEditWorkout(null); await onWorkoutSaved(workout.performed_on); }}/><button className="calendar-editor-close" onClick={() => setEditWorkout(null)}>×</button></div></div>}</>;
}
