import type { Folder, Routine } from '../routines/types';
import type { Workout } from '../workout/types';
import type { CalendarMonth, LoadCalendarMonth, CalendarDay } from './types';
import { useState, useEffect } from 'react';
import { today, duration } from '../../shared/lib/format';
import { api } from '../../shared/api/client';
import { RoutineEditor } from '../routines/RoutineEditor';

export function TrainingCalendar({ folders, history, months, loadMonth, start, repeatWorkout, viewWorkout, editWorkout, addNote }: { folders: Folder[]; history: Workout[]; months: Record<string, CalendarMonth>; loadMonth: LoadCalendarMonth; start: (routine: Routine) => Promise<void>; repeatWorkout: (workout: Workout) => Promise<void>; viewWorkout: (workout: Workout) => void; editWorkout: (workout: Workout) => void; addNote: (workout: Workout) => void }) {
    const routines = folders.flatMap(folder => folder.routines);
    const [plannedEdit, setPlannedEdit] = useState<Routine | null>(null);
    const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
    const [selected, setSelected] = useState(today());
    const [editing, setEditing] = useState(false);
    const [menuOpen, setMenuOpen] = useState(false);
    const [chosenRoutine, setChosenRoutine] = useState('');
    const [name, setName] = useState('My training week');
    const [assignments, setAssignments] = useState<Record<number, string>>({});
    const monthNumber = month.getMonth() + 1;
    const monthKey = `${month.getFullYear()}-${String(monthNumber).padStart(2, '0')}`;
    const data = months[monthKey];
    const plan = data?.plan ?? null;
    const days = data?.days ?? [];
    useEffect(() => { void loadMonth(month.getFullYear(), monthNumber); }, [month, monthNumber, loadMonth]);
    useEffect(() => { if (plan) { setName(plan.name); setAssignments(Object.fromEntries(plan.days.map(item => [item.weekday, String(item.routine_id)]))); } }, [plan]);
    const changeMonth = (offset: number) => { const next = new Date(month.getFullYear(), month.getMonth() + offset, 1); setMonth(next); setSelected(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-01`); };
    const save = async () => { const monday = new Date(); monday.setDate(monday.getDate() - ((monday.getDay() + 6) % 7)); const payload = { name, starts_on: monday.toISOString().slice(0, 10), days: Object.entries(assignments).filter(([, value]) => value).map(([weekday, routine_id]) => ({ weekday: Number(weekday), routine_id: Number(routine_id) })) }; try { await api('/calendar/plan', { method: 'POST', body: JSON.stringify(payload) }); await loadMonth(month.getFullYear(), monthNumber, true); setEditing(false); } catch { setEditing(true); } };
    const selectedDay = days.find(day => day.date === selected);
    const workout = history.find(item => item.completed && item.performed_on === selected);
    const template = selectedDay?.routine_override ?? routines.find(item => item.id === selectedDay?.routine_id) ?? routines.find(item => String(item.id) === chosenRoutine);
    const routine = template ? { ...template, scheduled_on: selected } : undefined;
    const eventName = selectedDay?.status === 'completed' ? selectedDay.workout_name : selectedDay?.routine_name;
    const date = new Date(`${selected}T12:00:00`);
    const firstOffset = (new Date(month.getFullYear(), month.getMonth(), 1).getDay() + 6) % 7;
    const dateKey = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
    const daysByDate = new Map(days.map(day => [day.date, day]));
    const selectedRoutine = routines.find(item => String(item.id) === chosenRoutine);
    const cells: { date: string; day?: CalendarDay; outside: boolean }[] = [];
    for (let index = 0; index < firstOffset; index++) { const d = new Date(month.getFullYear(), month.getMonth(), index - firstOffset + 1); cells.push({ date: dateKey(d), outside: true }); }
    const daysInMonth = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate();
    for (let dayNumber = 1; dayNumber <= daysInMonth; dayNumber++) { const key = dateKey(new Date(month.getFullYear(), month.getMonth(), dayNumber)); cells.push({ date: key, day: daysByDate.get(key), outside: false }); }
    while (cells.length % 7) { const d = new Date(month.getFullYear(), month.getMonth(), cells.length - firstOffset + 1); cells.push({ date: dateKey(d), outside: true }); }
    const primary = () => { if (workout) viewWorkout(workout); else if (routine) void start(routine); else setEditing(true); };
    return <section className="training-calendar">
        {plannedEdit && <RoutineEditor routine={plannedEdit} folders={folders} close={() => setPlannedEdit(null)} done={async () => { await loadMonth(month.getFullYear(), monthNumber, true); setPlannedEdit(null); }}/>}
        <header className="training-calendar-header"><h1>{month.toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</h1><div className="training-calendar-tools"><button className="calendar-icon-button previous" aria-label="Previous month" onClick={() => changeMonth(-1)}>‹</button><button className="calendar-icon-button next" aria-label="Next month" onClick={() => changeMonth(1)}>›</button><select aria-label="Routine" value={chosenRoutine} onChange={event => setChosenRoutine(event.target.value)}><option value="">{plan?.name.replace(/\\s+Program$/i, '') ?? 'Choose a routine'}</option>{routines.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="calendar-plan-button" onClick={() => setEditing(value => !value)}>{editing ? 'Close plan' : 'Plan week'}</button><div className="calendar-menu-wrap"><button className="calendar-icon-button calendar-menu-button" aria-label="Calendar options" aria-expanded={menuOpen} onClick={() => setMenuOpen(value => !value)}>⋯</button>{menuOpen && <div className="calendar-menu"><button onClick={() => { setSelected(today()); setMonth(new Date(new Date().getFullYear(), new Date().getMonth(), 1)); setMenuOpen(false); }}>Go to today</button><button onClick={() => { setEditing(true); setMenuOpen(false); }}>Edit weekly plan</button></div>}</div></div></header>
        {editing && <section className="week-planner"><label>WEEK NAME<input value={name} onChange={event => setName(event.target.value)}/></label><div>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((label, weekday) => <label key={label}><span>{label}</span><select value={assignments[weekday] ?? ''} onChange={event => setAssignments({ ...assignments, [weekday]: event.target.value })}><option value="">Rest day</option>{routines.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>)}</div><button className="primary" onClick={() => void save()}>Save weekly plan →</button></section>}
        <div className="training-calendar-layout"><div className="training-month"><div className="training-weekdays">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(label => <span key={label}>{label}</span>)}</div><div className="training-days">{cells.map(cell => { const day = cell.day; const label = day?.status === 'completed' ? day.workout_name : day?.routine_name; const shortLabel = label ? (/full body/i.test(label) ? 'Full' : label.split(' · ')[0].split(' ')[0]) : ''; const loggedWorkout = history.find(item => item.completed && item.performed_on === cell.date); const dayNote = loggedWorkout?.note; const eventRoutineId = day?.status === 'completed' ? loggedWorkout?.routine_id : day?.routine_id; const matchesFilter = !chosenRoutine || !label || (eventRoutineId != null ? String(eventRoutineId) === chosenRoutine : label.trim().toLocaleLowerCase() === selectedRoutine?.name.trim().toLocaleLowerCase()); return <button key={cell.date} type="button" className={`training-day ${day?.status ?? 'empty'} ${cell.outside ? 'outside' : ''} ${cell.date === selected ? 'selected' : ''} ${cell.date === today() ? 'today' : ''} ${matchesFilter ? '' : 'filtered-out'}`} onClick={() => { setSelected(cell.date); if (cell.outside) setMonth(new Date(`${cell.date}T12:00:00`)); }}><span className="training-date">{Number(cell.date.slice(-2))}</span>{dayNote && <span className="training-note-indicator" tabIndex={0} aria-label={`Workout note: ${dayNote}`}>✎<span className="training-note-tooltip" role="tooltip">{dayNote}</span></span>}{label && <span className="training-event"><b className="training-event-full">{label}</b><b className="training-event-short">{shortLabel}</b><small>{day?.status === 'completed' ? 'Completed' : day?.status === 'missed' ? 'Missed' : 'Planned'}</small><i aria-hidden="true">{day?.status === 'completed' ? '✓' : '●'}</i></span>}</button>; })}</div></div>
        <aside className="training-detail"><div className="training-detail-head"><h2><span className="training-detail-desktop-date">{date.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })}</span><span className="training-detail-mobile-date">{date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span></h2><p>{date.toLocaleDateString(undefined, { weekday: 'long' })}</p></div>{eventName ? <div className="training-detail-workout"><span className="training-detail-icon" aria-hidden="true">{workout ? '✓' : '▤'}</span><div><h3>{eventName}{workout?.note && <span className="training-detail-note-indicator" tabIndex={0} aria-label={`Workout note: ${workout.note}`}>✎<span className="training-note-tooltip" role="tooltip">{workout.note}</span></span>}</h3><p>{workout ? `${workout.exercises.reduce((total, exercise) => total + (exercise.sets?.length ?? 0), 0)} sets · ${duration(workout.duration_seconds)}` : selectedDay?.status === 'missed' ? 'Missed workout' : 'Planned workout'}</p></div></div> : <p className="training-detail-empty">No workout planned.</p>}<button className="training-detail-primary" onClick={primary}>{workout ? 'View workout' : routine ? 'Start workout' : 'Add workout'}</button><div className="training-detail-actions">{workout && <><button onClick={() => void repeatWorkout(workout)}>↻ <span>Log again</span>›</button><button onClick={() => editWorkout(workout)}>✎ <span>Edit workout</span>›</button><button onClick={() => addNote(workout)}>▤ <span>{workout.note ? 'Edit note' : 'Add note'}</span>›</button></>}{!workout && routine && <button onClick={() => setPlannedEdit(routine)}>▤ <span>Open planned workout</span>›</button>}</div></aside></div>
    </section>;
}
